/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/colors'
      | '/(main)/dashboard'
      | '/(main)/icon/ant'
      | '/(main)/shadow'
      | '/(main)/starter'
      | '/(main)/typography'
    >,
    '/(main)/colors': RouteRecordInfo<
      '/(main)/colors',
      '/colors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/dashboard': RouteRecordInfo<
      '/(main)/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/icon/ant': RouteRecordInfo<
      '/(main)/icon/ant',
      '/icon/ant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/shadow': RouteRecordInfo<
      '/(main)/shadow',
      '/shadow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/starter': RouteRecordInfo<
      '/(main)/starter',
      '/starter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/typography': RouteRecordInfo<
      '/(main)/typography',
      '/typography',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/login': RouteRecordInfo<
      '/authentication/login',
      '/authentication/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/authentication/register': RouteRecordInfo<
      '/authentication/register',
      '/authentication/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/coming-soon': RouteRecordInfo<
      '/maintenance/coming-soon',
      '/maintenance/coming-soon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error404': RouteRecordInfo<
      '/maintenance/error404',
      '/maintenance/error404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error500': RouteRecordInfo<
      '/maintenance/error500',
      '/maintenance/error500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/under-construction': RouteRecordInfo<
      '/maintenance/under-construction',
      '/maintenance/under-construction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/colors'
        | '/(main)/dashboard'
        | '/(main)/icon/ant'
        | '/(main)/shadow'
        | '/(main)/starter'
        | '/(main)/typography'
      views:
        | 'default'
    }
    'src/pages/(main)/colors.vue': {
      routes:
        | '/(main)/colors'
      views:
        | never
    }
    'src/pages/(main)/dashboard.vue': {
      routes:
        | '/(main)/dashboard'
      views:
        | never
    }
    'src/pages/(main)/icon/ant.vue': {
      routes:
        | '/(main)/icon/ant'
      views:
        | never
    }
    'src/pages/(main)/shadow.vue': {
      routes:
        | '/(main)/shadow'
      views:
        | never
    }
    'src/pages/(main)/starter.vue': {
      routes:
        | '/(main)/starter'
      views:
        | never
    }
    'src/pages/(main)/typography.vue': {
      routes:
        | '/(main)/typography'
      views:
        | never
    }
    'src/pages/authentication/login.vue': {
      routes:
        | '/authentication/login'
      views:
        | never
    }
    'src/pages/authentication/register.vue': {
      routes:
        | '/authentication/register'
      views:
        | never
    }
    'src/pages/maintenance/coming-soon.vue': {
      routes:
        | '/maintenance/coming-soon'
      views:
        | never
    }
    'src/pages/maintenance/error404.vue': {
      routes:
        | '/maintenance/error404'
      views:
        | never
    }
    'src/pages/maintenance/error500.vue': {
      routes:
        | '/maintenance/error500'
      views:
        | never
    }
    'src/pages/maintenance/under-construction.vue': {
      routes:
        | '/maintenance/under-construction'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
